theme: jekyll-theme-cayman

defaults:
  - scope:
      path: ""
    values:
      button_link: https://github.com/steven-xia/planet-wars-starterpackage
      button_text: View on GitHub

markdown: kramdown
kramdown:
  math_engine: katex